# Generated by Django 4.2.17 on 2025-01-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [('curator', '0001_initial')]

	operations = [
		migrations.CreateModel(
			name='CuratedDataset',
			fields=[
				('search_id', models.UUIDField(primary_key=True, serialize=False)),
				('search_url', models.URLField()),
				('search_results', models.JSONField(default='{}')),
				('created_time', models.DateTimeField(auto_now_add=True)),
				('updated_time', models.DateTimeField(auto_now=True))
			],
			options={
				'verbose_name': 'curated dataset',
				'verbose_name_plural': 'curated datasets',
				'db_table': 'curated_dataset',
				'managed': False
			}
		)
	]
